Features: Conditional Offer Constraints, Custom Env Variables, Node Taints are applied from K3s Arguments
AVENTER-UG/mesos-m3s pull request #22
Opened 2024-09-03 13:39 UTC by itsoksarvesh

Feature Implementation

- Conditional Hostname Offer Constraints... Will work only if Environment variable for conditional offer constraint is set and if Hostname constraints are set for all of DS, Server and Agent.. 
- Custom Env Variables - Feature to add custom env variables to the K3s Nodes while starting. Useful for having dynamic values per framework

Bugfix

- Delayed Node Taints Application - Node Taints are now applied from K3s Arguments. Older way of adding Node taints from controller is not yet decommissioned but will be decommisioned in the future unless there is a requirement for that. Currently the older way acts as a backup solution
- Offer Accepted even when required ports are not available
- Added Kafka Plugin Call for Mesos Subscribe Event

2024-09-09 11:44 UTC, andreaspeters requested changes

2024-09-25 15:51 UTC, itsoksarvesh commented on init.go
> +func getUniqueStringList(slice []string) []string {
Added a comment explaining the use of the function

2024-09-25 16:58 UTC, itsoksarvesh commented on scheduler/prepare.go
> +
Done

2024-09-26 02:22 UTC, itsoksarvesh commented on app.go
> +	framework.FrameworkInfo.Role = &framework.FrameworkRole
Changed to FrameworkInfo.Roles.. Needed to add MultiRole Capability for Roles & Offer constraints to work

2024-09-26 02:22 UTC, itsoksarvesh commented on scheduler/scheduler.go
> +		logrus.WithField("func", "mesos.Reconcile").Debug("Reconcile Task: ", task.TaskID, task.TaskName)
Changed to Debugf

2024-09-26 02:23 UTC, itsoksarvesh commented on init.go
> +	config.EnableHostnameOfferConstraint = stringToBool(util.Getenv("ENABLE_HOSTNAME_OFFER_CONSTRAINT", "true"))
Agreed.  Made the necessary changes

2024-09-26 02:23 UTC, itsoksarvesh commented on init.go
> +		if config.K3SServerConstraintHostname == "" || config.K3SAgentConstraintHostname == "" || config.DSConstraintHostname == "" {
Agreed.  Made the necessary changes

2024-10-11 05:51 UTC, itsoksarvesh commented
@andreaspeters My latest 2 commits on the iss-lab/mesos-m3s repo have also been added to this PR automatically since it was not closed earlier... The commits are for the following features

- Setting Mesos Resource allocation Limits on the M3s Tasks ... There are individual ENV variables that control the limits as well as a global flag which will control the enforcement of the limits .. I believe both are needed ... The global flag gives us control to set/unset limits whereas the individual env variables control what the limit is set for allowing for over-provisioning etc.
- Bugfix in the M3s Status API if kubernetes is not up.. There was a null pointer panic from kubernetes client...

2024-10-14 20:36 UTC, merged